apiVersion: v1
kind: Service
metadata:
  name: shipping-service

spec:
  selector:
    app: shipping-service
  ports:
  - port: 8600
    targetPort: 8600
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: sebasl07/shipping-service-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8600        
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_INSTANCE
          value: "shipping-service"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
