version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - ecommerce-net
  service-discovery-container:
    build:
      context: ./service-discovery
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  cloud-config-container:
    build:
      context: ./cloud-config
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  api-gateway-container:
    build:
      context: ./api-gateway
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  proxy-client-container:
    build:
      context: ./proxy-client
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  order-service-container:
    build:
      context: ./order-service
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  payment-service-container:
    build:
      context: ./payment-service
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  product-service-container:
    build:
      context: ./product-service
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  shipping-service-container:
    build:
      context: ./shipping-service
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  user-service-container:
    build:
      context: ./user-service
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
  favourite-service-container:
    build:
      context: ./favourite-service
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - ecommerce-net
networks:
  ecommerce-net:
    driver: bridge



