apiVersion: v1
kind: Service
metadata:
  name: product-service

spec:
  selector:
    app: product-service
  ports:
  - port: 8500
    targetPort: 8500
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: sebasl07/product-service-ecommerce-boot:0.1.0        
        ports:
        - containerPort: 8500
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_INSTANCE
          value: "product-service"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
