apiVersion: v1
kind: Service
metadata:
  name: service-discovery

spec:
  selector:
    app: service-discovery
  ports:
  - port: 8761
    targetPort: 8761
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: sebasl07/service-discovery-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
