apiVersion: v1
kind: Service
metadata:
  name: order-service

spec:
  selector:
    app: order-service
  ports:
  - port: 8300
    targetPort: 8300
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: sebasl07/order-service-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8300
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://cloud-config:9296"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
