version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      zipkin-container:
        condition: service_started
  cloud-config-container:
    build:
      context: ./cloud-config
      dockerfile: Dockerfile
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9296/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  api-gateway-container:
    image: selimhorri/api-gateway-ecommerce-boot:0.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  proxy-client-container:
    image: selimhorri/proxy-client-ecommerce-boot:0.1.0
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  order-service-container:
    image: selimhorri/order-service-ecommerce-boot:0.1.0
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  payment-service-container:
    image: selimhorri/payment-service-ecommerce-boot:0.1.0
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  product-service-container:
    image: selimhorri/product-service-ecommerce-boot:0.1.0
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:0.1.0
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  user-service-container:
    image: selimhorri/user-service-ecommerce-boot:0.1.0
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started
  favourite-service-container:
    image: selimhorri/favourite-service-ecommerce-boot:0.1.0
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
    depends_on:
      cloud-config-container:
        condition: service_healthy
      service-discovery-container:
        condition: service_healthy
      zipkin-container:
        condition: service_started